image: rust:1.85

stages:
  - build

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

cache:
  paths:
    - .cargo/
    - target/

windows-build:
  stage: build
  tags:
    - windows
  script:
    - curl -sSf https://sh.rustup.rs | sh -s -- -y
    - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
    - cargo test
    - cargo build --release
  artifacts:
    paths:
      - target/release/ohmylogcat.exe
    expire_in: 30 days
  only:
    - main
