[package]
name = "ohmylogcat"
version = "0.2.0"
description = "A lightweight Android Logcat viewer"
authors = ["jyy"]
edition = "2021"
repository = "https://github.com/jyy2luck/ohmylogcat"
homepage = "https://github.com/jyy2luck/ohmylogcat"

[dependencies]
ratatui = "0.29"
crossterm = "0.28"
tokio = { version = "1", features = ["rt-multi-thread", "process", "io-util", "sync", "time", "macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "6"
arboard = "3"
sys-locale = "0.3.2"
unicode-width = "0.2"
